version: "3.9"
services:
  tradebot:
    build: .
    command: ./dogebot.sh
    restart: always
    environment:
        BINANCE_SECRETS_FILE: ${BINANCE_SECRETS_FILE:-/secrets/binance.json}
        DOGEBOT_CONFIG: ${DOGEBOT_CONFIG:-/configs/dogebot.json}
    volumes:
        - sqlite-data:/sqlite-data
        - ./secrets:/secrets
        - ./configs:/configs

volumes:
  sqlite-data:
