#pragma once


namespace ad {
namespace tradebot {
namespace spawner {

// Design notes:
// After the initial `Sell`, spawn buy fragments for a proportion of the **quote** amount generated by the sale
// (the rest is the taken home).
// The **real** quote amount is considered. This is an important distiction if the sale took place at
// at a rate above the target.
// The buy fragments are distributed down following a discrete sequence of factors.
// The sum of factors has to be == 1 (the taken home being already removed from the distributed amount).
//
// After a `Buy`, spawn sell fragments at the parent's buy rate (thus cycling).
// TODO define if some is taken home
// It should be made sure that it does not lead to a lowering cycle: the base amount to sell
// should provide a quote amount at least equal to the quote amount spent during this `Buy`, plus
// some if some should be taken home after the `Sell`.
//
} // namespace spawner
} // namespace tradebot
} // namespace ad
